### ISSUE TITLE
模糊@问匹配错误

### ISSUE THREAD

**Issue by Nova-Noir** [kexue-z/nonebot-plugin-word-bank2#8]
在实际使用过程中，无论是使用`模糊@问<问题>答<回答>`还是使用`@模糊问<问题>答<回答>`
都无法正常回答，并报KeyError

使用测试用例中的`全局模糊@问 晚安 答 不准睡`也出现相同错误

Nonebot版本: `nonebot2@2.0.0b2`
word-bank2版本: `nonebot-plugin-word-bank2@0.1.3.1`
日志: <details>

```
02-28 15:10:19 [SUCCESS] nonebot | ONEBOT V11 2437618725 | [message.group.normal]: Message -722587760 from 4050909@[?:980392728] "模糊@问图2片答[CQ:image,file=3c05ba99d361aeb2143282c878b58fa8.image,url=https://gchat.qpic.cn/gchatpic_new/4050909/980392728-2945140926-3C05BA99D361AEB2143282C878B58FA8/0?term=2,subType=1]"
02-28 15:10:19 [DEBUG] nonebot | Checking for matchers in priority 1...
02-28 15:10:19 [INFO] nonebot | Event will be handled by <Matcher from src.plugins.nonebot_plugin_picsearcher, type=message, priority=1, temp=False>
02-28 15:10:19 [DEBUG] nonebot | Running matcher <Matcher from src.plugins.nonebot_plugin_picsearcher, type=message, priority=1, temp=False>
02-28 15:10:19 [DEBUG] nonebot | Running handler <Dependent call=<function handle_pic at 0x7fe909118550>, params=[ModelField(name='event', type=GroupMessageEvent, required=True), ModelField(name='state', type=Mapping[Any, Any], required=True)], parameterless=[]>
02-28 15:10:19 [INFO] nonebot | Matcher <Matcher from src.plugins.nonebot_plugin_picsearcher, type=message, priority=1, temp=False> running complete
02-28 15:10:19 [DEBUG] nonebot | Checking for matchers in priority 10...
02-28 15:10:19 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False>
02-28 15:10:19 [DEBUG] nonebot | Running matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False>
02-28 15:10:19 [DEBUG] nonebot | Running handler <Dependent call=<function handle_wb at 0x7fe90921a710>, params=[ModelField(name='event', type=MessageEvent, required=True)], parameterless=[]>
02-28 15:10:19 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False> running complete
02-28 15:10:19 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
02-28 15:10:19 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False>
02-28 15:10:19 [DEBUG] nonebot | Running matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False>
02-28 15:10:19 [DEBUG] nonebot | Running handler <Dependent call=<function wb_set at 0x7fe90921a830>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='event', type=MessageEvent, required=True), ModelField(name='matcher', type=Matcher, required=True), ModelField(name='matched', type=Tuple[str, ...], required=True)], parameterless=[]>
02-28 15:10:19 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
02-28 15:10:19 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False> running complete
02-28 15:10:19 [DEBUG] nonebot | Stop event propagation
02-28 15:10:20 [SUCCESS] nonebot | ONEBOT V11 2437618725 | [message.group.normal]: Message 1032686245 from 4050909@[?:980392728] "?2?"
02-28 15:10:20 [DEBUG] nonebot | Checking for matchers in priority 1...
02-28 15:10:20 [DEBUG] nonebot | Checking for matchers in priority 10...
02-28 15:10:20 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False>
02-28 15:10:20 [DEBUG] nonebot | Running matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False>
02-28 15:10:20 [DEBUG] nonebot | Running handler <Dependent call=<function handle_wb at 0x7fe90921a710>, params=[ModelField(name='event', type=MessageEvent, required=True)], parameterless=[]>
02-28 15:10:20 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False> running complete
02-28 15:10:20 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
02-28 15:10:20 [DEBUG] nonebot | Checking for matchers in priority 11...
02-28 15:10:26 [DEBUG] nonebot | OneBot V11 | User is calling me elaina
02-28 15:10:26 [SUCCESS] nonebot | ONEBOT V11 2437618725 | [message.group.normal]: Message 1250605619 from 4050909@[?:980392728] "?2?"
02-28 15:10:26 [DEBUG] nonebot | Checking for matchers in priority 1...
02-28 15:10:26 [DEBUG] nonebot | Checking for matchers in priority 10...
02-28 15:10:26 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False>
02-28 15:10:26 [DEBUG] nonebot | Running matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False>
02-28 15:10:26 [DEBUG] nonebot | Running handler <Dependent call=<function handle_wb at 0x7fe90921a710>, params=[ModelField(name='event', type=MessageEvent, required=True)], parameterless=[]>
02-28 15:10:26 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False> running complete
02-28 15:10:26 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_word_bank2, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/site-packages/nonebot/message.py", line 158, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/site-packages/nonebot/message.py", line 207, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/site-packages/nonebot/matcher.py", line 742, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/site-packages/nonebot/matcher.py", line 709, in simple_run
    await handler(
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 76, in __call__
    return await self.call(**values)
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/site-packages/nonebot_plugin_word_bank2/__init__.py", line 38, in handle_wb
    msgs = wb.match(
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/site-packages/nonebot_plugin_word_bank2/data_source.py", line 67, in match
    res = self.__match(index, msg, type_, to_me)
  File "/home/nonebot/.conda/envs/nonebot/lib/python3.10/site-packages/nonebot_plugin_word_bank2/data_source.py", line 91, in __match
    return bank[key]
KeyError: '图2片'
```

**Comment by Nova-Noir** [comment]
"/atme 图2片": [
                "[CQ:image,file=file:////home/nonebot/novabot/data/word_bank/img/3c05ba99d361aeb2143282c878b58fa8.image,url=https://gchat.qpic.cn/gchatpic_new/4050909/980392728-2945140926-3C05BA99D361AEB2143282C878B58FA8/0?term=2,subType=1]"
            ],

**Comment by kexue-z** [comment]
草 虽然我知道问题出在哪里 但是我不知道从哪里开始改，，，因为这一段不是我写的

**Comment by kexue-z** [comment]
#9 好了 大佬光速pr
